import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";
  const isLandingPage = pathname === "/" || pathname === "";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${isLandingPage ? "" : "flex"}`}>
        {!isLandingPage && <Sidebar />}
        <div className={isLandingPage ? "" : "flex-1 p-4"}>
          {!isLandingPage && <Header />}
          {children}
        </div>
      </body>
    </html>
  );
}